twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

# config/packages/twig.yaml
    globals:
      categoriesAll: '@App\Service\CategoriesManagement'
      programsAll: '@App\Service\ProgramsManagement'
