<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDrOMr2S\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDrOMr2S/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDrOMr2S.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDrOMr2S\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDrOMr2S\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DrOMr2S',
    'container.build_id' => 'a839bbd2',
    'container.build_time' => 1574435582,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDrOMr2S');
