<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA4cSRT2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA4cSRT2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA4cSRT2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA4cSRT2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA4cSRT2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'A4cSRT2',
    'container.build_id' => 'c6ef9127',
    'container.build_time' => 1574100410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA4cSRT2');
