<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8wcgjLb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8wcgjLb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8wcgjLb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8wcgjLb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8wcgjLb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8wcgjLb',
    'container.build_id' => 'f80f4c7b',
    'container.build_time' => 1573723719,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8wcgjLb');
